### ISSUE TITLE
Menda kamchilik. 

### ISSUE THREAD

**Issue by Komron1107** [Komron1107/dars-28#1]
![image](https://github.com/Komron1107/dars-28/assets/153824943/d5fafad1-923a-49e2-bd22-c217d1afd466)

Shu qismni centerga ololmadim. bir ko'rib bering.

**Comment by KeldiyorDev** [comment]
![image](https://github.com/Komron1107/dars-28/assets/96241234/ce8696a0-973a-4d8b-9b0c-02993529570a)

containerda kamchilik bor ekan. push qilib qo'ydim. ko'ring.
